/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#include "MainWindow.h"
#include "MainComponent.h"


//==============================================================================
MainAppWindow::MainAppWindow()
: DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),
                  Colours::black,
                  DocumentWindow::allButtons)
{
    setUsingNativeTitleBar (true);
    
    MainComponent* mainComponent = new MainComponent();
   
	setContentOwned (mainComponent, false);
	
    setResizable (true, false);
	centreWithSize (650, 425);
    
    setVisible (true);

}


MainAppWindow::~MainAppWindow()
{
}

void MainAppWindow::closeButtonPressed()
{
    JUCEApplication::getInstance()->systemRequestedQuit();
}
